const ALL_PRODUCTS_DATA = [
    // Masculino
    { id: 'MAS001', name: 'Casaco de Lã Clássico', category: 'masculino', type: 'casaco', price: 499.00, installments: '10x de R$ 49,90 sem juros', imagePath: 'imagens/CasacoMasculino/1.jpg', description: 'Casaco de lã premium para o inverno.', material: '80% Lã, 20% Poliéster.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#333', '#fff'] },
    { id: 'MAS002', name: 'Casaco Xadrez Elegante', category: 'masculino', type: 'casaco', price: 549.00, installments: '10x de R$ 54,90 sem juros', imagePath: 'imagens/CasacoMasculino/2.jpg', description: 'Casaco moderno com estampa xadrez.', material: '50% Lã, 50% Algodão.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#000', '#ccc'] },
    { id: 'MAS003', name: 'Moletom Canguru Preto', category: 'masculino', type: 'casaco', price: 169.00, installments: '5x de R$ 33,80 sem juros', imagePath: 'imagens/CasacoMasculino/3.jpg', description: 'Moletom casual e quente com bolso canguru.', material: '100% Algodão.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#000', '#fff'] },
    { id: 'MAS004', name: 'Jaqueta Esportiva Leve', category: 'masculino', type: 'casaco', price: 175.00, installments: '5x de R$ 35,00 sem juros', imagePath: 'imagens/CasacoMasculino/4.jpg', description: 'Jaqueta esportiva ideal para exercícios.', material: '100% Poliéster.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#000', '#333'] },
    { id: 'MAS005', name: 'Casaco Nylon Azul', category: 'masculino', type: 'casaco', price: 185.00, installments: '6x de R$ 30,83 sem juros', imagePath: 'imagens/CasacoMasculino/5.jpg', description: 'Casaco de nylon leve e resistente à água.', material: '100% Nylon.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#000080', '#fff'] },
    { id: 'MAS006', name: 'Jaqueta Corta-Vento', category: 'masculino', type: 'casaco', price: 159.00, installments: '5x de R$ 31,80 sem juros', imagePath: 'imagens/CasacoMasculino/6.jpg', description: 'Corta-vento básico para dias de vento.', material: '100% Poliéster.', folder: 'CasacoMasculino', imageCount: 6, colors: ['#000', '#666'] },

    { id: 'MAS007', name: 'Camisa Box Gueixa', category: 'masculino', type: 'camisa', price: 89.90, installments: '3x de R$ 29,96 sem juros', imagePath: 'imagens/CasacoMasculino/7.jpg', description: 'Camisa box com estampa artística.', material: '100% Algodão.', folder: 'CamisaMasculina', imageCount: 5, colors: ['#000', '#fff'] },
    { id: 'MAS008', name: 'Camisa Box Renascer', category: 'masculino', type: 'camisa', price: 89.90, installments: '3x de R$ 29,96 sem juros', imagePath: 'imagens/CamisaMasculina/1.jpg', description: 'Camisa box com estampa Renascer.', material: '100% Algodão.', folder: 'CamisaMasculina', imageCount: 5, colors: ['#000', '#fff'] },
    { id: 'MAS009', name: 'Camisa Geométrica', category: 'masculino', type: 'camisa', price: 94.90, installments: '3x de R$ 31,63 sem juros', imagePath: 'imagens/CamisaMasculina/2.jpg', description: 'Camisa com estampa geométrica moderna.', material: '100% Algodão.', folder: 'CamisaMasculina', imageCount: 5, colors: ['#000', '#fff'] },
    { id: 'MAS010', name: 'Camisa Retrô 90s', category: 'masculino', type: 'camisa', price: 84.90, installments: '3x de R$ 28,30 sem juros', imagePath: 'imagens/CamisaMasculina/3.jpg', description: 'Camisa com pegada vintage dos anos 90.', material: '100% Algodão.', folder: 'CamisaMasculina', imageCount: 5, colors: ['#000', '#fff'] },
    { id: 'MAS011', name: 'Camisa Minimalista', category: 'masculino', type: 'camisa', price: 79.90, installments: '2x de R$ 39,95 sem juros', imagePath: 'imagens/CamisaMasculina/4.jpg', description: 'Camisa básica de alta qualidade.', material: '100% Algodão.', folder: 'CamisaMasculina', imageCount: 5, colors: ['#000', '#fff'] },

    { id: 'MAS012', name: 'Short India Estampado', category: 'masculino', type: 'short', price: 79.90, installments: '2x de R$ 39,95 sem juros', imagePath: 'imagens/BermundaMasculina/1.jpg', description: 'Short masculino com estampa indiana.', material: '100% Poliéster.', folder: 'BermudaMasculina', imageCount: 5, colors: ['#666', '#800000'] },
    { id: 'MAS013', name: 'Short Surf Listrado', category: 'masculino', type: 'short', price: 84.90, installments: '3x de R$ 28,30 sem juros', imagePath: 'imagens/BermundaMasculina/2.jpg', description: 'Short ideal para praia e piscina.', material: '100% Poliéster.', folder: 'BermudaMasculina', imageCount: 5, colors: ['#000', '#fff'] },
    { id: 'MAS014', name: 'Short Chino Bege', category: 'masculino', type: 'short', price: 99.90, installments: '3x de R$ 33,30 sem juros', imagePath: 'imagens/BermundaMasculina/3.jpg', description: 'Short de sarja casual.', material: '100% Algodão.', folder: 'BermudaMasculina', imageCount: 5, colors: ['#f5f5dc', '#808000'] },
    { id: 'MAS015', name: 'Short Tactel Básico', category: 'masculino', type: 'short', price: 69.90, installments: '2x de R$ 34,95 sem juros', imagePath: 'imagens/BermundaMasculina/4.jpg', description: 'Short Tactel esportivo e leve.', material: '100% Poliéster.', folder: 'BermudaMasculina', imageCount: 5, colors: ['#000', '#333'] },
    { id: 'MAS016', name: 'Short Listras Modernas', category: 'masculino', type: 'short', price: 95.90, installments: '3x de R$ 31,96 sem juros', imagePath: 'imagens/BermundaMasculina/5.jpg', description: 'Short com listras coloridas.', material: '100% Algodão.', folder: 'BermudaMasculina', imageCount: 5, colors: ['#fff', '#333'] },

    // Feminino
    { id: 'FEM001', name: 'Camisa Básica Branca', category: 'feminino', type: 'camisa', price: 89.90, installments: '3x de R$ 29,96 sem juros', imagePath: 'imagens/CamisaFeminina/1.jpg', description: 'Camisa feminina básica e versátil.', material: '100% Algodão.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#333', '#fff'] },
    { id: 'FEM002', name: 'Camisa Cropped Estampada', category: 'feminino', type: 'camisa', price: 99.90, installments: '3x de R$ 33,30 sem juros', imagePath: 'imagens/CamisaFeminina/2.jpg', description: 'Cropped moderno com estampa floral.', material: '100% Viscose.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#f0f0f0'] },
    { id: 'FEM003', name: 'Camisa Gola V Manga Longa', category: 'feminino', type: 'camisa', price: 109.90, installments: '4x de R$ 27,48 sem juros', imagePath: 'imagens/CamisaFeminina/3.jpg', description: 'Camisa elegante com decote em V.', material: '95% Algodão, 5% Elastano.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#000', '#fff'] },
    { id: 'FEM004', name: 'Regata Floral', category: 'feminino', type: 'camisa', price: 79.90, installments: '2x de R$ 39,95 sem juros', imagePath: 'imagens/CamisaFeminina/4.jpg', description: 'Regata leve com estampa floral vibrante.', material: '100% Viscose.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#fff', '#f00'] },
    { id: 'FEM005', name: 'Baby Look Desenho', category: 'feminino', type: 'camisa', price: 89.90, installments: '3x de R$ 29,96 sem juros', imagePath: 'imagens/CamisaFeminina/5.jpg', description: 'Baby look com estampa divertida.', material: '100% Algodão.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#fff'] },
    { id: 'FEM006', name: 'Camisa Arte Exclusiva', category: 'feminino', type: 'camisa', price: 92.90, installments: '3x de R$ 30,97 sem juros', imagePath: 'imagens/CamisaFeminina/6.jpg', description: 'Camisa com arte exclusiva da marca Poisson.', material: '100% Algodão.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#000', '#fff'] },
    { id: 'FEM007', name: 'Camisa Slim Fit Cinza', category: 'feminino', type: 'camisa', price: 95.90, installments: '3x de R$ 31,97 sem juros', imagePath: 'imagens/CamisaFeminina/7.jpg', description: 'Modelagem slim fit que se ajusta ao corpo.', material: '95% Algodão, 5% Elastano.', folder: 'CamisaFeminina', imageCount: 7, colors: ['#4b5563', '#000'] },

    { id: 'FEM008', name: 'Short Jeans Frontal', category: 'feminino', type: 'short', price: 99.90, installments: '3x de R$ 33,30 sem juros', imagePath: 'imagens/BermudaFeminina/1.jpg', description: 'Short jeans de cintura alta, confortável.', material: '100% Algodão.', folder: 'BermudaFeminina', imageCount: 4, colors: ['#000', '#fff'] },
    { id: 'FEM009', name: 'Short Esportivo Listrado', category: 'feminino', type: 'short', price: 79.90, installments: '2x de R$ 39,95 sem juros', imagePath: 'imagens/BermudaFeminina/2.jpg', description: 'Short ideal para atividades físicas.', material: '100% Poliéster.', folder: 'BermudaFeminina', imageCount: 4, colors: ['#000', '#fff'] },
    { id: 'FEM010', name: 'Short Cintura Alta Sarja', category: 'feminino', type: 'short', price: 109.90, installments: '4x de R$ 27,48 sem juros', imagePath: 'imagens/BermudaFeminina/3.jpg', description: 'Short de sarja com modelagem elegante.', material: '100% Algodão.', folder: 'BermudaFeminina', imageCount: 4, colors: ['#000', '#fff'] },
    { id: 'FEM011', name: 'Short Moletinho Conforto', category: 'feminino', type: 'short', price: 89.90, installments: '3x de R$ 29,96 sem juros', imagePath: 'imagens/BermudaFeminina/4.jpg', description: 'Short de moletinho super macio.', material: '80% Algodão, 20% Poliéster.', folder: 'BermudaFeminina', imageCount: 4, colors: ['#6b7280'] },
];

const PRODUCTS_FOR_HOME = ALL_PRODUCTS_DATA;
